### ISSUE TITLE
Invalid Amount

### ISSUE THREAD

**Issue by dnl27** [paymill/paymill-magento-2#5]
Trying to process a payment with credit card I get the following JS error:

`Generating Token`
`Object { amount_int: NaN, currency: "EUR" }`
`field_invalid_amount`

It seems that Paymill needs the amount as an integer but in Magento the price format is decimal (100.00€).

I'm using Magento 2.1.3

Is there any solution for this problem?
Thanks in advance.

**Comment by ekarakashi** [comment]
Thank you for submitting this issue.

We fixed and tested it.

Please take a look, hopefully everything should be as expected.

Cheers
